### ISSUE TITLE
[Bug] Error: Could not load the "sharp" module using the darwin-x64 runtime

### ISSUE THREAD

**Issue by cdwmhcc** [oliverschwendener/ueli#1123]
**Describe the bug**
```
Uncaught Exception:
Error: Could not load the "sharp" module using the darwin-x64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
npm install --include=optional sharp
yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
npm install --os=darwin --cpu=x64 sharp
- Consult the installation documentation:
See https://sharp.pixelplumbing.com/install
at Object.<anonymous> (/Applications/Ueli.app/Contents/Resources/app.asar/node_modules/sharp/lib/sharp.js:114:9)
at Module._compile (node:internal/modules/cjs/loader:1391:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1451:10)
at Module.load (node:internal/modules/cjs/loader:1214:32)
at Module._load (node:internal/modules/cjs/loader:1030:12)
at c._load (node:electron/js2c/node_init:2:13672)
at Module.require (node:internal/modules/cjs/loader:1242:19)
at require (node:internal/modules/helpers:176:18)
at Object.<anonymous> (/Applications/Ueli.app/Contents/Resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
at Module._compile (node:internal/modules/cjs/loader:1391:14)
```
**To Reproduce**
1. Go to [v9.0.0](https://github.com/oliverschwendener/ueli/releases/tag/v9.0.0) 
2. Download: https://github.com/oliverschwendener/ueli/releases/download/v9.0.0/Ueli-9.0.0-universal.dmg
3. Install
4. Open

**Expected behavior**
Open and use normally

**Screenshots**
![image](https://github.com/oliverschwendener/ueli/assets/8030134/7dcd5edb-7fb3-476e-9a27-3e8d418cbb7a)

**Environment**
 - OS: macos
 - Version 9.0

**Comment by oliverschwendener** [comment]
I guess you're using a macOS computer with an Intel chip?

**Comment by cdwmhcc** [comment]
> I guess you're using a macOS computer with an Intel chip?

Yes, the bottom of the issue is marked as macOS, and the error message also mentions darwin-x64

**Comment by oliverschwendener** [comment]
Can you download the latest release from [here](https://github.com/oliverschwendener/ueli/releases) and try again? Make sure to download the correct binary for your computer:

![image](https://github.com/oliverschwendener/ueli/assets/15727229/ef17a54b-545a-4f26-865a-41f08ae815c4)
