### ISSUE TITLE
[Bug] Unsupported macOS version: 24.0.0

### ISSUE THREAD

**Issue by brianjor** [oliverschwendener/ueli#1243]
**Describe the bug**
Ueli fails to start with an error

**To Reproduce**
1. Try to start Ueli
2. Error window pops up

**Expected behavior**
Ueli starts

**Screenshots**
![Screenshot 2024-11-04 at 1 42 06 PM](https://github.com/user-attachments/assets/3997a4c2-4cd1-4d17-9ede-97b6f9878b3e)

**Environment**
 - OS: See screenshot
 - Node: v18.19.1

**Additional context**
Stopped working after macOS update.

**Comment by brianjor** [comment]
Here's a text copy of the error:
```
Uncaught Exception:
Error: Unsupported macOS version: 24.0.0
at /Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:8:603562
at t.getOperatingSystemVersion (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:8:603608)
at 22991 (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:8:947291)
at n (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:8:2373418)
at /Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:8:2373928
at Object.<anonymous> (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:8:2373938)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
```

**Comment by oliverschwendener** [comment]
I guess you're using ueli v8 which is discontinued. I suggest updating to ueli v9.

**Comment by erhanbicer** [comment]
in my opinion, v8 ui is better than v9. can you fix this problem, please?
