### ISSUE TITLE
[Bug] Ueli renders with blank window

### ISSUE THREAD

**Issue by IrishBruse** [oliverschwendener/ueli#1298]
Ueli seems to display a blank screen on both Mac M3 and Linux Mint with the latest update 9.14 Running on Mac the only error I can see is deprecated warning the textured window type is deprecated

I'll try run the dev build on Linux later and report back if infind anything

Seems like on Mac I'm seeing error the textured window type is deprecated and will be removed

**Environment**
 - OS: [macOS|Linux]
 - Version [e.g. 9.14.0]

**Comment by oliverschwendener** [comment]
Strange, I tested it on all platforms. Is it only happening in dev mode? Did you install the npm packages with `npm install`?

**Comment by IrishBruse** [comment]
Not tried it in dev mode yet I reverted to .13 on mac and its back working I'm using brew

**Comment by oliverschwendener** [comment]
What version of macOS are you using?

**Comment by IrishBruse** [comment]
14.6.1
Just installed the arm version from github to verify its not a brew issue same blank screen

**Comment by oliverschwendener** [comment]
Is the settings window also blank?

**Comment by oliverschwendener** [comment]
I think the textured warning is not causing the problem as that has been there for a while, see here: https://github.com/electron/electron/issues/44688

**Comment by econneely** [comment]
Settings is blank too if i open it from the context menu as the button is invisible 
![image](https://github.com/user-attachments/assets/86886a1b-9940-4222-802c-1bec1dd7335f)
just clones it on the mac and ran npm run dev and its also blank i can seem to open the dev tools either so not sure how to debug this 🤔

**Comment by oliverschwendener** [comment]
Can you open the dev tools (Cmd+shift+i) and see if there is some errors?

**Comment by econneely** [comment]
```
chunk-WFILHHV3.js?v=c25442a9:21609 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
2useScrollbar.ts:4 Uncaught TypeError: Cannot read properties of undefined (reading 'colorNeutralBackground4')
    at useScrollBar (useScrollbar.ts:4:83)
    at App (App.tsx:31:5)
    at renderWithHooks (chunk-WFILHHV3.js?v=c25442a9:11596:26)
    at mountIndeterminateComponent (chunk-WFILHHV3.js?v=c25442a9:14974:21)
    at beginWork (chunk-WFILHHV3.js?v=c25442a9:15962:22)
    at HTMLUnknownElement.callCallback2 (chunk-WFILHHV3.js?v=c25442a9:3680:22)
    at Object.invokeGuardedCallbackDev (chunk-WFILHHV3.js?v=c25442a9:3705:24)
    at invokeGuardedCallback (chunk-WFILHHV3.js?v=c25442a9:3739:39)
    at beginWork$1 (chunk-WFILHHV3.js?v=c25442a9:19818:15)
    at performUnitOfWork (chunk-WFILHHV3.js?v=c25442a9:19251:20)
chunk-WFILHHV3.js?v=c25442a9:14080 The above error occurred in the <App> component:

    at App (http://localhost:7777/Core/App.tsx:30:50)
    at ThemeProvider (http://localhost:7777/Core/Theme/ThemeProvider.tsx:31:33)
    at Router (http://localhost:7777/@fs/Users/econneely/git/ueli/node_modules/.vite/deps/chunk-M4YXJ2CZ.js?v=c25442a9:4447:15)
    at HashRouter (http://localhost:7777/@fs/Users/econneely/git/ueli/node_modules/.vite/deps/react-router-dom.js?v=c25442a9:586:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ chunk-WFILHHV3.js?v=c25442a9:14080
Show 1 more frame
Show less
chunk-WFILHHV3.js?v=c25442a9:19466 Uncaught TypeError: Cannot read properties of undefined (reading 'colorNeutralBackground4')
    at useScrollBar (useScrollbar.ts:4:83)
    at App (App.tsx:31:5)
    at renderWithHooks (chunk-WFILHHV3.js?v=c25442a9:11596:26)
    at mountIndeterminateComponent (chunk-WFILHHV3.js?v=c25442a9:14974:21)
    at beginWork (chunk-WFILHHV3.js?v=c25442a9:15962:22)
    at beginWork$1 (chunk-WFILHHV3.js?v=c25442a9:19806:22)
    at performUnitOfWork (chunk-WFILHHV3.js?v=c25442a9:19251:20)
    at workLoopSync (chunk-WFILHHV3.js?v=c25442a9:19190:13)
    at renderRootSync (chunk-WFILHHV3.js?v=c25442a9:19169:15)
    at recoverFromConcurrentError (chunk-WFILHHV3.js?v=c25442a9:18786:28)
VM4 sandbox_bundle:2 Electron Security Warning (Disabled webSecurity) This renderer process has "webSecurity" disabled. This
  exposes users of this app to severe security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ VM4 sandbox_bundle:2
VM4 sandbox_bundle:2 Electron Security Warning (allowRunningInsecureContent) This renderer process has "allowRunningInsecureContent"
  enabled. This exposes users of this app to severe security risks.

  
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ VM4 sandbox_bundle:2
```

**Comment by econneely** [comment]
```
{
    "appearance.customDarkThemeVariants": {
        "10": "#35A854",
        "20": "#35A854",
        "30": "#35A854",
        "40": "#35A854",
        "50": "#35A854",
        "60": "#35A854",
        "70": "#35A854",
        "80": "#35A854",
        "90": "#35A854",
        "100": "#35A854",
        "110": "#35A854",
        "120": "#35A854",
        "130": "#35A854",
        "140": "#35A854",
        "150": "#35A854",
        "160": "#35A854"
    },
    "appearance.searchBarAppearance": "outline",
    "appearance.searchBarPlaceholderText": "Type to search...",
    "appearance.themeName": "Custom",
    "extension[VSCode].command": "code %s",
    "extension[VSCode].prefix": "",
    "extension[Workflow].workflows": [
        {
            "actions": [],
            "name": "",
            "id": "workflow-02874b14-0bf0-431b-9f8a-ac415f01dd21"
        }
    ],
    "extensions.enabledExtensionIds": [
        "Workflow",
        "SimpleFileSearch",
        "UeliCommand",
        "JetBrainsToolbox",
        "Calculator",
        "Base64Conversion",
        "WebSearch",
        "DeeplTranslator",
        "CurrencyConversion",
        "ColorConverter",
        "ApplicationSearch",
        "VSCode"
    ],
    "general.hotkey": "Super+Space",
    "general.language": "en-US",
    "general.searchHistory.enabled": true,
    "general.searchHistory.history": [
        "0x204*3+0xC28",
        "0x204*3+0x10",
        "0xAEC0+0x274",
        "0x18B0-0x1840",
        "0x18B0-",
        "0x10+0xC28+(0x204 *3)",
        "0x10+0xC28+0x204 *3",
        "0xC28+0x204 *3",
        "0x204 *3",
        "0x204*3"
    ],
    "general.searchHistory.limit": 10,
    "imageGenerator.faviconApiProvider": "Favicone",
    "keyboardAndMouse.singleClickBehavior": "invokeSearchResultItem",
    "searchEngine.fuzziness": 0.5,
    "searchEngine.id": "fuzzysort",
    "searchEngine.rescanIntervalInSeconds": 300,
    "window.alwaysCenter": false,
    "window.alwaysOnTop": false,
    "window.defaultSettingsWindowSize": {
        "width": 800,
        "height": 600
    },
    "window.defaultWindowSize": {
        "width": 600,
        "height": 400
    },
    "window.hideWindowOn": [
        "blur",
        "afterInvocation",
        "escapePressed"
    ],
    "window.scrollBehavior": "instant"
}
```

**Comment by econneely** [comment]
Ah seems to be a bug if you were using the custom color scheme which seems to have been removed

**Comment by econneely** [comment]
![image](https://github.com/user-attachments/assets/28fa14e4-4fdf-4922-b289-b2ae36cf7242)

**Comment by oliverschwendener** [comment]
Ah yes, thanks for the hint. My bad. I guess the current implementation is not good enough. If the theme name set in the settings is not found, then it should fall back to the Fluent UI Web theme. I'll create a fix. Thanks for reporting!

**Comment by oliverschwendener** [comment]
A fix for this should be included in the next release
