### ISSUE TITLE
[Feature Request] add more filtering options in File Search

### ISSUE THREAD

**Issue by femto-code** [oliverschwendener/ueli#503]
Just found a bug in the everything command line integration under Windows:

Error in debug.log after trying: `es?ext:pdf size:>1MB`

```
Error: Command failed: cmd /c chcp 65001>nul && "C:\Program Files\Everything\es.exe" -max-results 24 ext:pdf size:>1MB
Zugriff verweigert

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

Everything doc says:
>Use ^ to escape \, &, |, >, < and ^.

So the error is related to a lacking escape of the command line parameters. But I think this can be fixed very quickly.
Thank you in advance!

**Comment by oliverschwendener** [comment]
I think this was fixed with https://github.com/oliverschwendener/ueli/releases/tag/v9.17.0.
