### ISSUE TITLE
not update index

### ISSUE THREAD

**Issue by 4shizzlemanizze** [oliverschwendener/ueli#533]
![ueli_Z1lDmKVb1x](https://user-images.githubusercontent.com/72236696/94877680-e5e20380-0463-11eb-8a3f-63e0ed401660.png)
hi,
not update index
since version ueli-8.1.1
windows 7 x64

**Comment by AmrBinBashir** [comment]
Can you post your debug logs ?
![image](https://user-images.githubusercontent.com/48618675/94996545-9f94bd80-05a5-11eb-955d-12f410e6f854.png)

**Comment by christian-456** [comment]
hi,
i have the same problem as the user 4shizzlemanizze
i also use Windows 7 64-bit and the problem exists since Ueli 8.1.1
and without indexing no programs can be launched

**debug logs from today:**
2020-12-07T01:19:13.616Z error: Command failed: powershell -NonInteractive -NoProfile -Command "& { [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; Get-ChildItem -Path 'C:\Users\Mephisto'  | Where { $_.FullName.Length -gt 0 } | % { $_.FullName } | Select-Object -First 1000 }"

Error: Command failed: powershell -NonInteractive -NoProfile -Command "& { [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; Get-ChildItem -Path 'C:\Users\Mephisto'  | Where { $_.FullName.Length -gt 0 } | % { $_.FullName } | Select-Object -First 1000 }"

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-12-07T14:39:23.843Z error: Command failed: powershell -NonInteractive -NoProfile -Command "& { [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; Get-ChildItem -Path 'C:\Users\Mephisto'  | Where { $_.FullName.Length -gt 0 } | % { $_.FullName } | Select-Object -First 1000 }"

Error: Command failed: powershell -NonInteractive -NoProfile -Command "& { [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; Get-ChildItem -Path 'C:\Users\Mephisto'  | Where { $_.FullName.Length -gt 0 } | % { $_.FullName } | Select-Object -First 1000 }"

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2020-12-07T16:57:26.111Z debug: Check for updates
2020-12-07T16:57:28.150Z debug: Update check result: update not available

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
