### ISSUE TITLE
UWP applications are not indexed

### ISSUE THREAD

**Issue by extesy** [oliverschwendener/ueli#610]
Ueli doesn't show any of my installed UWP apps. During reindexing it shows `RangeError: stdout maxBuffer length exceeded` error box and also has this in the log file:

```
2020-12-25T21:01:53.392Z error: stdout maxBuffer length exceeded
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:372:14)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by oliverschwendener** [comment]
@tkohlmeier Can we limit the output of the powershell script that provides all info on the UWP apps?

**Comment by tkohlmeier** [comment]
I think we should rather move from `child_process.exec` to `child_process.spawn` for this. `spawn` returns a stream so it should work with any stdout length.

More details: https://www.hacksparrow.com/nodejs/difference-between-spawn-and-exec-of-node-js-child-rocess.html
