### ISSUE TITLE
URL Plugin fails for users with ZScaler

### ISSUE THREAD

**Issue by densom** [oliverschwendener/ueli#619]
This is due to the custom certificate authority used for SSL inspection by ZScaler.  We typically use a .pem file to resolve this issue in other software.

![2021-01-07_17h10_42](https://user-images.githubusercontent.com/1593598/103950672-4a6bc900-510b-11eb-99d8-73c8a1689c03.png)

Here is the debug log:

```
2021-01-07T15:15:08.589Z error: self signed certificate in certificate chain
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1484:34)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket._finishInit (_tls_wrap.js:927:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:697:12)
```

**Comment by nperanzi** [comment]
I am also experiencing this issue, which appears to be driven by ZScaler's Internet Security plugin, although it seems the specific error message has changed as per below. 

![image](https://user-images.githubusercontent.com/7450800/177895633-f9722721-0e5c-432b-a378-d5cf02620382.png)

Here is the debug log:
```
2022-07-08T01:01:30.534Z error: unable to get local issuer certificate
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
```

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
