### ISSUE TITLE
Control panel plugin seems to be broken

### ISSUE THREAD

**Issue by r57zone** [oliverschwendener/ueli#625]
![](https://user-images.githubusercontent.com/9499881/104463744-974c1580-55cb-11eb-84b3-b3690a10a2a9.png)

Hi, Control panel plugin seems to be broken.

OS: Windows 10 x64 ver 2004

`Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json" Get-ControlPanelItem : Object reference not set to an instance of an object. At line:1 char:1 + Get-ControlPanelItem | ConvertTo-Json + ~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
`

**Comment by tkohlmeier** [comment]
Could you please run the command `Get-ControlPanelItem` in a powershell window? Do you get a list of control panel items or an error?

**Comment by r57zone** [comment]
The command is working
![](https://user-images.githubusercontent.com/9499881/104694662-f3767d00-5724-11eb-8d9e-3f589fcade09.png)

**Comment by tkohlmeier** [comment]
What about this command (run from cmd.exe)?

    powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"

**Comment by r57zone** [comment]
Works
![](https://user-images.githubusercontent.com/9499881/104813233-52b9b780-5821-11eb-8401-cf6a5a024bb3.png)

**Comment by tkohlmeier** [comment]
That is really strange... Could you look for a related error in the debug log and post it?

![grafik](https://user-images.githubusercontent.com/6824291/105147754-e4674480-5b01-11eb-8b17-f3c7d4ec7546.png)

**Comment by r57zone** [comment]
`2021-01-12T21:21:05.836Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:21:11.252Z debug: 0/330 app icons already exist
2021-01-12T21:21:11.252Z debug: Started to generate 330 app icons to C:\Users\r\.ueli\application-icons
2021-01-12T21:21:18.547Z error: Other instance is already running: quitting app.
2021-01-12T21:21:30.777Z debug: Successfully generated 330 icons
2021-01-12T21:23:59.745Z debug: Check for updates
2021-01-12T21:24:01.804Z debug: Update check result: update not available
2021-01-12T21:26:05.619Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:26:09.438Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:27:16.929Z debug: Check for updates
2021-01-12T21:27:17.948Z debug: Update check result: update not available
2021-01-12T21:31:33.957Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:31:38.170Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:32:28.554Z debug: Check for updates
2021-01-12T21:32:31.060Z debug: Update check result: update not available
2021-01-12T21:33:33.953Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-12T21:33:46.744Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:33:51.474Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:34:08.546Z debug: Check for updates
2021-01-12T21:34:10.649Z debug: Update check result: update not available
2021-01-12T21:34:13.085Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-12T21:35:06.218Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-12T21:36:08.394Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:36:13.224Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:36:17.941Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:37:04.957Z debug: Check for updates
2021-01-12T21:37:07.381Z debug: Update check result: update not available
2021-01-12T21:37:14.693Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-12T21:38:21.010Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:38:24.701Z debug: Check for updates
2021-01-12T21:38:25.156Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:38:27.299Z debug: Update check result: update not available
2021-01-12T21:49:59.089Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:50:03.024Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:54:20.714Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:54:26.150Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:54:26.207Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:54:31.086Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:54:34.807Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:54:39.144Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:54:43.221Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-12T21:54:45.962Z debug: Check for updates
2021-01-12T21:54:47.271Z debug: Skipping app icon generation. All app icons already exist
2021-01-12T21:54:48.442Z debug: Update check result: update not available
2021-01-12T21:54:54.097Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-12T21:55:02.308Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-13T14:13:08.207Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-13T14:13:12.163Z debug: 328/331 app icons already exist
2021-01-13T14:13:12.163Z debug: Started to generate 3 app icons to C:\Users\r\.ueli\application-icons
2021-01-13T14:13:13.333Z debug: Successfully generated 3 icons
2021-01-13T14:13:15.194Z debug: Check for updates
2021-01-13T14:13:17.670Z debug: Update check result: update not available
2021-01-13T14:13:20.023Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-13T14:17:41.878Z debug: Check for updates
2021-01-13T14:17:42.890Z debug: Update check result: update not available
2021-01-13T14:17:46.426Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-13T14:18:07.835Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-13T14:18:09.752Z debug: Skipping app icon generation. All app icons already exist
2021-01-13T14:23:07.843Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-13T14:23:09.925Z debug: Skipping app icon generation. All app icons already exist
2021-01-13T14:28:07.811Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-13T14:28:09.800Z debug: Skipping app icon generation. All app icons already exist
2021-01-20T08:56:04.406Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-20T08:56:07.311Z debug: 328/330 app icons already exist
2021-01-20T08:56:07.311Z debug: Started to generate 2 app icons to C:\Users\r\.ueli\application-icons
2021-01-20T08:56:08.213Z debug: Successfully generated 2 icons
2021-01-20T08:56:13.778Z debug: Check for updates
2021-01-20T08:56:15.944Z debug: Update check result: update not available
2021-01-20T08:56:23.813Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-20T08:56:31.966Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-20T08:56:43.512Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\r\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2021-01-20T08:56:45.319Z debug: Skipping app icon generation. All app icons already exist
2021-01-20T08:56:47.386Z error: Other instance is already running: quitting app.
2021-01-20T08:56:50.413Z debug: Check for updates
2021-01-20T08:56:52.469Z debug: Update check result: update not available
2021-01-20T08:57:10.771Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-20T08:58:02.646Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
2021-01-20T08:58:11.893Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

Error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command "Get-ControlPanelItem | ConvertTo-Json"
Get-ControlPanelItem : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-ControlPanelItem | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-ControlPanelItem], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.GetControlPanelItemCommand
 

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
`

**Comment by myxmaster** [comment]
This seems to be an internal error occurring within the Get-ControlPanelItem command. I have no explanation why it only happens when executed by ueli. Did you run the command as the same user and with the same privileges as ueli?

Searching for `"GetControlPanelItemCommand"` with Google yields zero results, so this seems to be very uncommon.

Are you able to open the control panel? Is something strange there, like missing icons?

You could also try to create another Windows account and run ueli there. Does that work?

**Comment by tkohlmeier** [comment]
This seems to be an internal error occurring within the Get-ControlPanelItem command. I have no explanation why it only happens when executed by ueli. Did you run the command as the same user and with the same privileges as ueli?

Searching for "GetControlPanelItemCommand" with Google yields zero results, so this seems to be very uncommon.

Are you able to open the control panel? Is something strange there, like missing icons?

You could also try to create another Windows account and run ueli there. Does that work?

**Comment by r57zone** [comment]
I tried to run as administrator and just with normal rights, the result is the same.

There are no problems with the control panel, no missing icons.

I'll try to check it later from another Windows account.

**Comment by ahrooran-r** [comment]
> Could you please run the command `Get-ControlPanelItem` in a powershell window? Do you get a list of control panel items or an error?

Hi. I also had the above issue and when I ran the command on powershell it didn't work. I am getting this error in terminal: 
`Get-ControlPanelItem: The term 'Get-ControlPanelItem' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

Further commands also failed. What can I do now? Is it a problem with Powershell the version is 7.1.3

Thanks in advance

**Comment by tkohlmeier** [comment]
Hi,

looks like PowerShell 7 no longer includes the commannd `Get-ControlPanelItem`.
It is described here: https://docs.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7

I think the only solution is to install an older version of PowerShell.
