### ISSUE TITLE
"Currency Converter" plugin error

### ISSUE THREAD

**Issue by krisu5** [oliverschwendener/ueli#734]
For example, this input gives me error: `10.56 USD to EUR` (and every other currency related).

**Log:**
```
2021-06-05T19:54:46.756Z error: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:38:265493
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Ueli version:** 8.12.0
**OS:** Windows 10 Pro, 20H2

**Comment by krisu5** [comment]
Never mind, this is duplicate issue: #680
