### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by adburbs** [oliverschwendener/ueli#833]
Getting this error on Mac Monterey

Uncaught Exception:
Error: Unsupported macOS version: 21.1.0
at /Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:1711443
at Object.t.getOperatingSystemVersion (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:1711489)
at Object.49989 (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:1942270)
at r (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:2245316)
at /Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:2245826
at Object.<anonymous> (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:2245836)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)

**Comment by oliverschwendener** [comment]
See #832 ;)
