### ISSUE TITLE
A JavaScript error occurred in the main process (macOS 21.2.0)

### ISSUE THREAD

**Issue by TSSlade** [oliverschwendener/ueli#853]
```
Uncaught Exception:
Error: Unsupported macOS version: 21.2.0
at /Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:1711443
at Object.t.getOperatingSystemVersion (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:1711489)
at Object.49989 (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:1942270)
at r (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:2245316)
at /Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:2245826
at Object.<anonymous> (/Applications/ueli.app/Contents/Resources/app.asar/bundle/main.js:2:2245836)
at Module._compile (internal/modules/cjs/loader.js:1152:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
```

Presumably related to #832, albeit not fixed by the 2021-11-08 upgrade.

**Comment by oliverschwendener** [comment]
I assume this is resolved. Feel free to reopen.
