### ISSUE TITLE
not support m1

### ISSUE THREAD

**Issue by lzq2357** [oliverschwendener/ueli#858]
i build ueli on my macbookair m1, build and package success, but throw exception when run it

Uncaught Exception:
Error: dlopen(/var/folders/gr/1vx5x9xx4qq3cvg8tt931f7h0000gn/T/.com.electron.ueli.LO8825, 0x0001): tried: '/var/folders/gr/1vx5x9xx4qq3cvg8tt931f7h0000gn/T/.com.electron.ueli.LO8825' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/.com.electron.ueli.LO8825' (no such file), '/usr/lib/.com.electron.ueli.LO8825' (no such file), '/private/var/folders/gr/1vx5x9xx4qq3cvg8tt931f7h0000gn/T/.com.electron.ueli.LO8825' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/.com.electron.ueli.LO8825' (no such file), '/usr/lib/.com.electron.ueli.LO8825' (no such file)
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
at Module.load (internal/modules/cjs/loader.js:992:32)
at Module._load (internal/modules/cjs/loader.js:885:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
at Module.require (internal/modules/cjs/loader.js:1032:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/Applications/ueli.app/Contents/Resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
at Module._compile (internal/modules/cjs/loader.js:1152:30)

**Comment by oliverschwendener** [comment]
This issue should be fixed, please let me know if it's still an issue.
