### ISSUE TITLE
wea? command not working

### ISSUE THREAD

**Issue by ahsanfarooq210** [oliverschwendener/ueli#868]
wea? command (weather)  is not working. following is the error message in the logs

2022-01-25T11:54:50.943Z error: certificate has expired
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)

**Comment by oliverschwendener** [comment]
Closing this issue as the weather plugin will be discontinued with ueli v9 (unless someone take their time to implement it).
