### ISSUE TITLE
error spawn: unknown

### ISSUE THREAD

**Issue by Malaombra** [oliverschwendener/ueli#890]
up till now i've been using the app with no problem, now nothing work anymore, i've reinstalled  it multiple times, but nothing seems to work 

2022-04-23T07:49:32.524Z error: spawn UNKNOWN
Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:412:11)
    at spawn (node:child_process:707:9)
    at Object.execFile (node:child_process:334:17)
    at Object.t.<computed> [as execFile] (node:electron/js2c/asar_bundle:5:2196)
    at exec (node:child_process:235:25)
    at node:electron/js2c/asar_bundle:5:12692
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:8:670674
    at new Promise (<anonymous>)
    at i (C:\Program Files\ueli\resources\app.asar\bundle\main.js:8:670643)
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:8:669821

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
