### ISSUE TITLE
Control panel plugin is broken?Can't search the item in Control panel

### ISSUE THREAD

**Issue by zomboo** [oliverschwendener/ueli#899]
Can't search the items in Control panel .
and when on/off the setting , show the picture like the attachment.
![image](https://user-images.githubusercontent.com/3627672/164142048-076890ab-b255-4c48-a7e9-026ae49a371c.png)

OS：windows 11
ueli：8.21.0
Electron：17.1.2
Node：16.13.0
V8：9.8.177.11-electron.0

debug.log : 
    at JSON.parse (<anonymous>)
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:8:757223
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-20T02:48:53.513Z debug: Skipping app icon generation. All app icons already exist
2022-04-20T02:48:54.237Z error: Unexpected token D in JSON at position 1
SyntaxError: Unexpected token D in JSON at position 1
    at JSON.parse (<anonymous>)
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:8:757223
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-20T02:52:57.754Z error: Other instance is already running: quitting app.
2022-04-20T02:53:06.212Z debug: Skipping app icon generation. All app icons already exist
2022-04-20T02:53:16.053Z error: Unexpected token D in JSON at position 1
SyntaxError: Unexpected token D in JSON at position 1
    at JSON.parse (<anonymous>)
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:8:757223
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-20T02:58:05.807Z debug: Skipping app icon generation. All app icons already exist
2022-04-20T02:58:06.547Z error: Unexpected token D in JSON at position 1
SyntaxError: Unexpected token D in JSON at position 1
    at JSON.parse (<anonymous>)
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:8:757223
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-20T03:00:17.029Z debug: Check for updates
2022-04-20T03:00:22.185Z debug: Update check result: update not available
2022-04-20T03:00:25.232Z error: Unexpected token D in JSON at position 1
SyntaxError: Unexpected token D in JSON at position 1
    at JSON.parse (<anonymous>)
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:8:757223
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-20T03:03:05.311Z debug: Skipping app icon generation. All app icons already exist
2022-04-20T03:03:05.650Z debug: Successfully refreshed all indexes

**Comment by oliverschwendener** [comment]
Closing this issue as the Control Panel plugin will be discontinued with ueli v9, unless someone takes their time to implement it.
